# Generated by Django 5.0.1 on 2024-03-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HDRAPP', '0002_video_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Register',
        ),
    ]
