# Generated by Django 5.0.1 on 2024-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDRAPP', '0004_video_add_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_no', models.BigIntegerField()),
                ('address_one', models.CharField(max_length=100)),
                ('address_two', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('skill', models.CharField(max_length=50)),
                ('experience', models.FloatField()),
                ('image', models.FileField(upload_to='Images/')),
            ],
        ),
    ]
