# Generated by Django 5.0.1 on 2024-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDRAPP', '0006_job_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profile',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
