# Generated by Django 5.0.1 on 2024-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDRAPP', '0008_userotp_userverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
        migrations.AlterField(
            model_name='userverification',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
