# Generated by Django 5.0.1 on 2024-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDRAPP', '0009_remember_delete_userotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Images/')),
                ('experience', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Remember',
        ),
    ]
